/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CalendarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// views/calendar-view.ts
var import_obsidian = require("obsidian");
var VIEW_TYPE_CALENDAR = "calendar-view";
var CalendarView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
    this.selectedDate = null;
    this.calendarContainer = null;
    this.notesContainer = null;
    this.currentDate = /* @__PURE__ */ new Date();
  }
  getViewType() {
    return VIEW_TYPE_CALENDAR;
  }
  getDisplayText() {
    return "Calendar";
  }
  onOpen() {
    return __async(this, null, function* () {
      this.createCalendarView();
      this.registerEvent(this.app.vault.on("create", () => this.updateNotesList()));
      this.registerEvent(this.app.vault.on("delete", () => this.updateNotesList()));
      this.registerEvent(this.app.vault.on("rename", () => this.updateNotesList()));
    });
  }
  onClose() {
    return __async(this, null, function* () {
    });
  }
  createCalendarView() {
    const container = this.contentEl;
    container.empty();
    const mainContainer = container.createDiv("calendar-main-container");
    const header = mainContainer.createDiv("calendar-header");
    const prevButton = header.createEl("button", { text: "\u2190" });
    prevButton.addClass("calendar-nav-button");
    prevButton.onclick = () => this.previousMonth();
    const monthDisplay = header.createDiv("calendar-month-display");
    monthDisplay.setText(this.formatMonthYear(this.currentDate));
    const nextButton = header.createEl("button", { text: "\u2192" });
    nextButton.addClass("calendar-nav-button");
    nextButton.onclick = () => this.nextMonth();
    this.calendarContainer = mainContainer.createDiv("calendar-grid-container");
    this.renderCalendar();
    this.notesContainer = mainContainer.createDiv("calendar-notes-container");
    this.updateNotesList();
  }
  renderCalendar() {
    if (!this.calendarContainer) return;
    this.calendarContainer.empty();
    const daysOfWeek = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
    daysOfWeek.forEach((day) => {
      const dayLabel = this.calendarContainer.createDiv("calendar-day-label");
      dayLabel.setText(day);
    });
    const year = this.currentDate.getFullYear();
    const month = this.currentDate.getMonth();
    const firstDay = new Date(year, month, 1).getDay();
    const daysInMonth = new Date(year, month + 1, 0).getDate();
    for (let i = 0; i < firstDay; i++) {
      this.calendarContainer.createDiv("calendar-empty-day");
    }
    for (let day = 1; day <= daysInMonth; day++) {
      const dayCell = this.calendarContainer.createDiv("calendar-day");
      dayCell.setText(day.toString());
      const date = new Date(year, month, day);
      dayCell.onclick = () => this.selectDate(date);
      if (this.selectedDate && this.isSameDay(date, this.selectedDate)) {
        dayCell.addClass("calendar-day-selected");
      }
      if (this.hasNotesForDate(date)) {
        dayCell.addClass("calendar-day-has-notes");
      }
    }
  }
  selectDate(date) {
    this.selectedDate = date;
    this.renderCalendar();
    this.updateNotesList();
  }
  previousMonth() {
    this.currentDate = new Date(
      this.currentDate.getFullYear(),
      this.currentDate.getMonth() - 1,
      1
    );
    this.renderCalendar();
    this.updateNotesList();
  }
  nextMonth() {
    this.currentDate = new Date(
      this.currentDate.getFullYear(),
      this.currentDate.getMonth() + 1,
      1
    );
    this.renderCalendar();
    this.updateNotesList();
  }
  updateNotesList() {
    if (!this.notesContainer || !this.selectedDate) {
      if (this.notesContainer) {
        this.notesContainer.empty();
        const emptyMsg = this.notesContainer.createDiv("calendar-notes-empty");
        emptyMsg.setText("Select a date to view notes");
      }
      return;
    }
    this.notesContainer.empty();
    const notes = this.getNotesForDate(this.selectedDate);
    if (notes.length === 0) {
      const emptyMsg = this.notesContainer.createDiv("calendar-notes-empty");
      emptyMsg.setText(`No notes for ${this.formatDate(this.selectedDate)}`);
      return;
    }
    const header = this.notesContainer.createDiv("calendar-notes-header");
    header.setText(`Notes for ${this.formatDate(this.selectedDate)} (${notes.length})`);
    const notesList = this.notesContainer.createDiv("calendar-notes-list");
    notes.forEach((note) => {
      const noteItem = notesList.createDiv("calendar-note-item");
      const noteLink = noteItem.createEl("a");
      noteLink.href = "#";
      noteLink.setText(note.basename || note.name);
      noteLink.onclick = (e) => {
        e.preventDefault();
        this.app.workspace.getLeaf(false).openFile(note);
      };
    });
  }
  getNotesForDate(date) {
    const notes = [];
    this.app.vault.getMarkdownFiles().forEach((file) => {
      if (this.isNoteCreatedOnDate(file, date)) {
        notes.push(file);
      }
    });
    return notes.sort((a, b) => a.basename.localeCompare(b.basename));
  }
  hasNotesForDate(date) {
    return this.app.vault.getMarkdownFiles().some(
      (file) => this.isNoteCreatedOnDate(file, date)
    );
  }
  isNoteCreatedOnDate(file, date) {
    const fileDate = new Date(file.stat.ctime);
    return this.isSameDay(fileDate, date);
  }
  isSameDay(date1, date2) {
    return date1.getDate() === date2.getDate() && date1.getMonth() === date2.getMonth() && date1.getFullYear() === date2.getFullYear();
  }
  formatDate(date) {
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    const year = date.getFullYear();
    return `${year}-${month}-${day}`;
  }
  formatMonthYear(date) {
    const months = [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December"
    ];
    return `${months[date.getMonth()]} ${date.getFullYear()}`;
  }
};

// main.ts
var CalendarPlugin = class extends import_obsidian2.Plugin {
  onload() {
    return __async(this, null, function* () {
      console.log("Loading Obsidian Calendar Plugin");
      this.registerView(
        VIEW_TYPE_CALENDAR,
        (leaf) => new CalendarView(leaf)
      );
      this.addRibbonIcon("calendar-glyph", "Open Calendar", () => __async(this, null, function* () {
        yield this.activateView();
      }));
      this.addCommand({
        id: "open-calendar",
        name: "Open Calendar View",
        callback: () => __async(this, null, function* () {
          yield this.activateView();
        })
      });
      this.app.workspace.onLayoutReady(() => {
        this.activateView();
      });
    });
  }
  onunload() {
    console.log("Unloading Obsidian Calendar Plugin");
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_CALENDAR);
  }
  activateView() {
    return __async(this, null, function* () {
      try {
        const { workspace } = this.app;
        let leaf = null;
        const leaves = workspace.getLeavesOfType(VIEW_TYPE_CALENDAR);
        if (leaves.length > 0) {
          leaf = leaves[0];
        } else {
          leaf = workspace.getRightLeaf(false);
          if (leaf) {
            yield leaf.setViewState({ type: VIEW_TYPE_CALENDAR, active: true });
          }
        }
        if (leaf) {
          workspace.revealLeaf(leaf);
        }
      } catch (error) {
        console.error("Failed to activate calendar view:", error);
      }
    });
  }
};
